---
git:
  depth: 10
sudo: false
language: node_js
cache: yarn

node_js:
- '7'
- '6'
- '4'

script:
- if [ -n "${LINT-}" ]; then yarn run lint ; fi
- if [ -n "${SMOKE-}" ]; then node smoke/run.js $SMOKE; fi
- if [ -z "${SKIPTESTS-}" ]; then yarn run test-ci; fi

matrix:
  include:
    - node_js: "node"
      env: LINT=true SKIPTESTS=true
    - node_js: "node"
      env: SMOKE=html-minifier SKIPTESTS=true
    - node_js: "node"
      env: SMOKE=jquery SKIPTESTS=true
    - node_js: "node"
      env: SMOKE=immutable-js SKIPTESTS=true

after_success: yarn run coverage-ci
